# Generated by Django 6.0.3 on 2026-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('certificate_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Valid Certificate', max_length=50)),
            ],
        ),
    ]
