# Generated by Django 6.0.3 on 2026-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('course_name', models.CharField(max_length=200)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('test_completed', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('student_name', 'email', 'course_name')},
            },
        ),
    ]
